# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [9]:
# Exercise 1.3
import numpy as np

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)


[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [1]:
#Exercise 1.4.1
import numpy as np
arr = np.array([12, 24, 36, 48, 60])
print(arr)
print(arr[0])
print(arr[2])

[12 24 36 48 60]
12
36


In [10]:
# Exersice 1.4.2
import numpy as np
arr = np.array([[5, 10, 15],
[20, 25, 30]])
print(arr)
print(arr[1, 1])

[[ 5 10 15]
 [20 25 30]]
25


In [3]:
# Exersice 1.4.3
import numpy as np
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])
result = arr[2:6]
print(result)

[ 6  8 10 12]


In [4]:
#Exersice 1.4.4
import numpy as np
numbers = np.array([45, 12, 78, 3, 30])
words = np.array(["orange", "apple", "banana", "kiwi"])
print(np.sort(numbers))
print(np.sort(words))

[ 3 12 30 45 78]
['apple' 'banana' 'kiwi' 'orange']


In [6]:
#Exercise 1.5
import numpy as np 
# Given array
arr = np.array([3, 2, 14, 9, 10, 12]) 
# Find the indexes where the value is 9
indexes = np.where(arr == 9) 
print("Indexes where value is 9:", indexes)

Indexes where value is 9: (array([3]),)


In [8]:
#Exercise 1.6
import numpy as np 
# Given arrays 
arr1 = np.array([9, 5, 8]) 
arr2 = np.array([55, 89, 76]) 
# Join the two arrays 
result = np.concatenate((arr1, arr2)) 
# Print the result 
print(result)

[ 9  5  8 55 89 76]
